<?php

/*
 * Menu Structure
 * "Name" => [
 *      Route::Tag
 * ]
 */
$aConfig['MODULE']['{module}']['Menu'] = [

    // Name
    'frontend' => [
        'PullDown Menu' => [ # Array key names can also be freely assigned and do not need to correspond to an existing tag
             'info',
             '403',
             '404',
             'imprint',
             'privacyPolicy',
        ],
        'info',
        '403',
        '404',
        'imprint',
        'privacyPolicy',
    ],
];
