<?php

/**
 * queue key
 * - Do not use special characters, spaces
 * - Underscore `_`, full stop `.` and colon `:` are ok
 *
 * worker class
 * - absolute address for the method (as for routing; see /etc/routing/*.php files)
 */
$aConfig['MODULE']['{module}']['queue']['worker'] = [

    // queue key
    //                                      responsible worker class address
    #'Foo::bar'                        => '\{module}\Model\Worker\Foo',
];
