<?php

/**
 * - register your db table classes as public properties.
 * - add a doctype to each static property
 * - these doctypes must contain the vartype information about the certain class
 * @example
 *      @var {module}\Model\DB\Table\Example
 *      public $o{module}ModelDBTableExample;
 * ---
 * [!]  it is important to declare the vartype expanded with a full path
 *      avoid to make use of `use ...` support
 *      otherwise the classes could not be read correctly
 */

namespace {module}\Model\DB\Collection;

use App\Table\TraitAppTableGroup;
use App\Table\TraitAppTableQueue;
use App\Table\TraitAppTableUser;
use MVC\DB\Model\DbCollection;
use MVC\DB\Trait\TraitDbInit;

/**
 * DB
 */
class DB extends DbCollection
{
    use TraitDbInit;

    #-------------------------------------------------------------------------------------------------------------------
    # tables

    use TraitAppTableQueue;
    use TraitAppTableUser;
    use TraitAppTableGroup;
}
