<?php

/**
 * - register your db table classes as public properties.
 * - add a doctype to each static property
 * - these doctypes must contain the vartype information about the certain class
 * @example
 *      @var {module}\Model\DB\Table\Example
 *      public $o{module}ModelDBTableExample;
 * ---
 * [!]  it is important to declare the vartype expanded with a full path
 *      avoid to make use of `use ...` support
 *      otherwise the classes could not be read correctly
 */

namespace {module}\Model\DB\Collection;

use MVC\DB\Model\DbCollection;
use MVC\DB\Trait\TraitDbInit;

/**
 * DB
 */
class DB extends DbCollection
{
    use TraitDbInit;

    /*
     * To instantiate all tables:
     * It is sufficient to get object vars of DB class once: `get_object_vars(\{module}\Model\DB::init());`
     */

    /**
     * @var \App\Table\Queue
     */
    public $oAppTableQueue {get => $this->activate(__PROPERTY__);}

    /**
     * @var \App\Table\User
     */
    public $oAppTableUser {get => $this->activate(__PROPERTY__);}

    /**
     * @var \App\Table\Group
     */
    public $oAppTableGroup {get => $this->activate(__PROPERTY__);}
}
