<?php

#-------------------------------------------------------------------------------------------------------------------
# queue / worker

// Auto-Routes for Worker:
// Automatically builds callable routes for each queue key,
// placed in config `etc/config/Foo/config/_queue.php`.
//
// e.g.: the Route "/_mvc/queue/worker/Email::new" is created for queue key `Email::new`
// so each queue key can be called with its own route
// Syntax:
//      /_mvc/queue/worker/{QUEUE KEY}
//
// the Target is to call the Route and get the Worker to run
// which is associated with it in that config file

// automatically builds callable, unique `\MVC\Route` routes for each queue job key
\MVC\Worker::workerAutoRoute();

// adds a route for calling worker getting queue jobs done
//              '/~/queue/run'                    '\App\Controller\Queue::run'
\MVC\Route::GET(\MVC\Config::get_MVC_QUEUE_RUN(), \MVC\Config::get_MVC_QUEUE_RUN_CLASSMETHOD());

#-------------------------------------------------------------------------------------------------------------------
# cron

// adds a route for calling cron jobs
//              '/~/cron/run'                     '\App\Controller\Cron::run'
\MVC\Route::GET(\MVC\Config::get_MVC_CRON_ROUTE(), \MVC\Config::get_MVC_CRON_RUN_CLASSMETHOD());
