<?php

// - add your db table classes as public properties
// - add a doctype `@var ...` to each property, containing the var type information about the certain class
// - declare the var type expanded with a full path; otherwise the classes could not be read correctly
// example:
///**
// * @example
// * @var {module}\Model\Table\Example
// */
//public $oFooModelTableExample {get => $this->activate(__PROPERTY__);}


namespace {module}\Model\DB\Collection;

use MVC\DB\Model\DbCollection;
use MVC\DB\Trait\DbCollectionTrait;

class {class} extends DbCollection
{
    use DbInitTrait;

    /*
     * To instantiate all tables of this collection: `get_object_vars(\{module}\Model\DB::init());`
     */
}