<?php

# List of Emvicy Standard Events
# @see https://emvicy.com/1.x/events#EmvicyStandardEvents


\MVC\Event::processBindConfigStack([

    'policy.index.requestMethodHasToMatchRouteMethod.after' => [

        /**
         * this is Middleware to
         * \{module}\Policy\Index::requestMethodHasToMatchRouteMethod
         */
        function (\MVC\DataType\DTArrayObject $oDTArrayObject) {

            // build message
            $sMessage = $oDTArrayObject->getDTKeyValueByKey('sMethod')->get_sValue()
                        . ', ' . ((true === $oDTArrayObject->getDTKeyValueByKey('bGrant')->get_sValue()) ? 'ALLOW' : 'DENY') . ', '
                        . 'Has to be: '. implode('|',\MVC\Route::getCurrent()->get_methodsAssigned())
                        . ' - Is: ' . \MVC\Request2::in()->get_requestMethod();

            // write message back to object
            $oDTArrayObject->setDTKeyValueByKey(
                \MVC\DataType\DTKeyValue::create()
                    ->set_sKey('sMessage')
                    ->set_sValue($sMessage)
            );

            if (true === \MVC\Config::get_MVC_LOG_POLICY())
            {
                // log request
                \MVC\Log::write(
                    \MVC\Request2::in()->get_path()
                    . ' (' . \MVC\Request2::in()->get_requestMethod() . ') => '
                    . \MVC\Route::getCurrent()->get_requestMethod() . ' '
                    . \MVC\Route::getCurrent()->get_path(),
                    \MVC\Config::get_MVC_LOG_FILE_POLICY(),
                    false
                );

                // log policy rule result
                \MVC\Log::write(
                    $oDTArrayObject->getDTKeyValueByKey('sMessage')
                        ->get_sValue(),
                    \MVC\Config::get_MVC_LOG_FILE_POLICY(),
                    false
                );
            }
        },
    ],
]);