<?php

/**
 * @name ${module}Controller
 */
namespace {module}\Controller;

use App\Controller;
    use MVC\DataType\DTRequestIn;
use MVC\DataType\DTRoute;
use MVC\MVCTrait\TraitDataType;

/**
 * @extends Controller
 */
class _Master extends Controller
{
    use TraitDataType;

    /**
     * @return void
     * @throws \ReflectionException
     */
    public static function __preconstruct()
    {
        parent::__preconstruct();
    }

    /**
     * @param \MVC\DataType\DTRequestIn $oDTRequestIn
     * @param \MVC\DataType\DTRoute     $oDTRoute
     * @throws \ReflectionException
     */
    public function __construct(DTRequestIn $oDTRequestIn, DTRoute $oDTRoute)
	{
        parent::__construct($oDTRequestIn, $oDTRoute);

        // View
        if (true === $this->isPrimary())
        {
            if (false === function_exists('{module}\Controller\view'))
            {
                /**
                 * @return \{module}\View\Index|\MVC\View|null
                 */
                function view() {return \{module}\View\Index::init();}
            }
        }
        else
        {
            \{module}\View\Index::init();
        }
    }

    public function __destruct()
    {
        ;
    }
}
