<?php

/**
 * @name ${module}Controller
 */
namespace {module}\Controller;

use App\Model\Menu;
use MVC\ArrDot;
use MVC\Config;
use MVC\DataType\DTRequestIn;
use MVC\DataType\DTRoute;

/**
 * @extends \{module}\Controller\_Master
 */
class Index extends _Master
{
    /**
     * @return void
     * @throws \ReflectionException
     */
    public static function __preconstruct()
    {
        parent::__preconstruct();
    }

    /**
     * @param \MVC\DataType\DTRequestIn $oDTRequestIn
     * @param \MVC\DataType\DTRoute     $oDTRoute
     * @throws \ReflectionException
     */
    public function __construct(DTRequestIn $oDTRequestIn, DTRoute $oDTRoute)
    {
        parent::__construct($oDTRequestIn, $oDTRoute);

        Menu::buildAllMenus(
            new ArrDot(Config::MODULE()['Menu']),
            bGetProptertiesFromRouteOnTag: true,
            sCallback: '\App\Model\Menu::buildBootstrap5Menu'
        );
    }

    /**
     * @param \MVC\DataType\DTRequestIn $oDTRequestCurrent
     * @param \MVC\DataType\DTRoute     $oDTRoute
     * @return void
     * @throws \ReflectionException
     */
	public function index(DTRequestIn $oDTRequestCurrent, DTRoute $oDTRoute)
	{
        \{module}\View\Index::init()->autoAssign();
	}

    /**
     * @param \MVC\DataType\DTRequestIn $oDTRequestCurrent
     * @param \MVC\DataType\DTRoute     $oDTRoute
     * @return void
     * @throws \ReflectionException
     */
    public function notFound(DTRequestIn $oDTRequestCurrent, DTRoute $oDTRoute)
    {
        \MVC\Http\Status_Not_Found_404::header();
        \{module}\View\Index::init()->autoAssign();
    }

    /**
     * @throws \ReflectionException
     * @throws \SmartyException
     */
    public function __destruct ()
    {
        \{module}\View\Index::init()->render();
    }
}