<?php
/**
 * Index.php
 *
 * @package Emvicy
 * @copyright ueffing.net
 * @author Guido K.B.W. Üffing <emvicy@ueffing.net>
 * @license GNU GENERAL PUBLIC LICENSE Version 3. See application/doc/COPYING
 */

/**
 * @name ${module}View
 */
namespace {module}\View;

use App\View;
use MVC\Http\Header;
use MVC\MVCTrait\TraitViewInit;

/**
 * Index
 * @extends \MVC\View
 */
class Index extends View
{
    use TraitViewInit;

    /**
     * Index constructor.
     * @throws \ReflectionException
     */
    protected function __construct()
    {
        parent::__construct();
        Header::init()->ContentSecurityPolicy();

        $this->sContentVar = 'sContent';
        $this->caching = false;
    }
}